version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: delivery-db-container
    volumes:
      - delivery_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    restart: no
volumes:
  delivery_postgres_data:
    driver: local